sudo: required

dist: trusty

language: php

git:
  depth: 1

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - if [ "$TRAVIS_PHP_VERSION" != "5.6" ]; then  travis_retry ./vendor/bin/phpunit; fi
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then  travis_retry ./vendor/bin/phpunit --coverage-clover coverage.xml; fi

after_success:
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml -B $TRAVIS_BRANCH; fi
