sudo: required

dist: trusty

language: php

git:
  depth: 1

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: 7.2
    - php: nightly
  fast_finish: true

before_install:
  - docker pull mongo
  - docker run -d -p 27017:27017 mongo
  - docker ps -a
  - pecl install mongodb-alpha
  - phpenv config-add ./travis/php.ini

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist
  - travis_retry composer require alcaeus/mongo-php-adapter
  - travis_retry composer require doctrine/mongodb:dev-master
  - travis_retry composer require doctrine/mongodb-odm:dev-master

script:
  - if [ "$TRAVIS_PHP_VERSION" != "5.6" ]; then  travis_retry bash -x ./travis/run-tests.sh; fi
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then  COVERAGE="--coverage-clover=coverage.xml" travis_retry bash -x ./travis/run-tests.sh; fi

after_success:
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml -B $TRAVIS_BRANCH; fi
